### ISSUE TITLE
cis194: Homework seven not running under GHC 8.10.2

### ISSUE THREAD

**Issue by Time0o** [bitemyapp/learnhaskell#149]
Executing `runhaskell StringBufEditor.hs` from Yorgey's seventh homework with GHC 8.10.2 results in:

```
Editor.hs:38:22: error:
    • No instance for (Applicative (Editor b))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monad (Editor b))
   |
38 |   deriving (Functor, Monad, MonadIO, MonadState (b,Int))
   |        
```

A fix could be provided or at least a remark included in the cis194 section.
